### ISSUE TITLE
Usage of the Arduino Wire library.

### ISSUE THREAD

**Issue by Koepel** [langston-stem/rocsat-c-2018#1]
In a number of files I noticed the wrong use of the Wire library.
After a Wire.requestFrom() there is no need to wait for something, you can remove all the ...WaitForBits() functions.
The Wire.beginTransmission() and Wire.endTransmission() should not be used together with Wire.requestFrom().
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1, 2 and 3.

**Comment by dlech** [comment]
Thanks for the tip. :smiley:
